name: BrianJWeichel
favicon: null
layout_spectrum: 0.9317746474407613
typography_spectrum: 0.7260235729627311
title: 'Mortgage Life '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.2740449372213334
  lightness: 0.007393145468086004
  saturation: 0.23152367258444428
  rhythmicContrast: 0.3365956791676581
purpose: []
